tab: 0
visualization:
  display:
    show_seq_lines: false
    circle_radius: 3.0
    summary_show_active: true
    summary_show_inputs: true
    summary_show_ces_pos: true
    summary_show_ces_neg: true
    video_summary_on_map: false
  runtime:
    tick_ms: 100
    max_iter: 0
    seq_window: 9
    avg_activity_window: 100
    summary_depth: 1000
    video_summary_height: 40
last_yaml: /home/speakup/homeProjects/CharlieLastMarks/charly6/brain.yaml
